"""
Created on July 29, 2025

@author: Jiale Lao

ThalamusDB runner implementation for movie use case.
"""

# =============================================================================
# 教学注释 pass — ThalamusDB × movie scenario (Hybrid mode + 8 inline SQL queries)
# =============================================================================
# Movie scenario: Movies + Reviews 两表, 跑 review sentiment 分析.
# Hybrid mode (paper-original SQPE 独家): 这个 runner 用 inline SQL string (写在
# _execute_q<i>() Python 方法里), 不读 files/movie/query/thalamusdb/Q*.sql.
# 与 cars/medical scenario 相反 (那两个用 SQL 文件 + 无 _execute_q* 方法).
#
# 8 queries (Q1-Q8) 全部走 NLfilter('positive'/'negative') + 一些 NLjoin (same/opposite
# sentiment). 涵盖 ThalamusDB 主要功能展示:
#   - Q1-Q4: NLfilter + count/select/ratio (aggregation)
#   - Q5-Q7: NLjoin pair-wise (same/opposite sentiment 对)
#   - Q8: CASE WHEN NLfilter + GROUP BY (分组统计)
#
# 数据建表逻辑 (__init__):
#   1. 调 super().__init__ 触发 scenario_handler.setup_scenario() — 生成 CSV
#      (Movies.csv + Reviews.csv) 到 files/movie/data/sf_<N>/
#   2. DuckDB connect → SHOW TABLES → 空则 read_csv + CREATE TABLE
#   3. 表名: Movies / Reviews (跟 inline SQL 字段对齐)
#
# 注意 default model = gemini-2.5-flash; 不传 Q text 文件 → execute_query 会
# 因 FileNotFoundError fallback 到 _execute_q<id>() 方法 (Hybrid 路径).
# =============================================================================
import os
from typing import Dict, Any
from pathlib import Path
import duckdb
import pandas as pd

# if you use local thalamusdb codes, please uncomment the following codes
# import sys

# sys.path.append(str(Path(__file__).parent.parent.parent.parent))
# tdb_path = str(
#     Path(__file__).parent.parent.parent.parent.parent
#     / "runner"
#     / "generic_thalamusdb_runner"
# )
# sys.path.insert(0, tdb_path)
# end of local codes version

from runner.generic_thalamusdb_runner.generic_thalamusdb_runner import (
    GenericThalamusDBRunner,
)


class ThalamusDBRunner(GenericThalamusDBRunner):
    """ThalamusDB runner for movie use case."""

    def __init__(
        self,
        use_case: str,
        scale_factor: int,
        model_name: str = "gemini-2.5-flash",
        concurrent_llm_worker: int = 20,
        skip_setup: bool = False,
    ):
        """
        Initialize ThalamusDB runner for movie case.

        Args:
            use_case: The use case to run
            model_name: LLM model to use
            concurrent_llm_worker: Number of concurrent workers
        """
        # Set database path to movie database
        db_name = "movie_database.duckdb"
        db_folder = (
            Path(__file__).resolve().parents[5] / "files" / use_case / "data" / f"sf_{scale_factor}"
        )
        db_path = db_folder / db_name

        # IMPORTANT: Call parent init FIRST to trigger data generation via setup_scenario()
        # This must happen before we try to read CSV files
        super().__init__(
            use_case, scale_factor, model_name, concurrent_llm_worker, db_path,
            skip_setup=skip_setup
        )

        # Now create the tables if they don't exist (data should be generated by now)
        # Note: The database file may already exist (created by parent init),
        # so we check for tables instead of file existence
        conn = duckdb.connect(db_path)
        tables = conn.execute("SHOW TABLES").fetchall()

        if len(tables) == 0:
            # Step 1: Read CSVs (these should exist now after setup_scenario)
            movies_df = pd.read_csv(f"{db_folder}/Movies.csv")
            reviews_df = pd.read_csv(f"{db_folder}/Reviews.csv")

            # Step 2: Save DataFrames as persistent tables
            conn.register("movies_df", movies_df)
            conn.register("reviews_df", reviews_df)

            conn.execute("CREATE TABLE Movies AS SELECT * FROM movies_df")
            conn.execute("CREATE TABLE Reviews AS SELECT * FROM reviews_df")
            print("Database tables created successfully")

        conn.close()

    def _execute_q1(self) -> Dict[str, Any]:
        """
        Q1: Five clearly positive reviews (any movie)
        """
        sql_query = """
        select reviewId from Reviews where NLfilter(reviewText, 'the review sentiment is positive') limit 5
        """

        return self.execute_thalamusdb_query(sql_query)

    def _execute_q2(self) -> Dict[str, Any]:
        """
        Q2: Five positive reviews for movie `taken_3`
        """
        sql_query = """
        select reviewId from Reviews 
        where id = 'taken_3' 
        and NLfilter(reviewText, 'the review sentiment is positive')
        limit 5
        """
        return self.execute_thalamusdb_query(sql_query)

    def _execute_q3(self) -> Dict[str, Any]:
        """
        Q3: Count of positive reviews for movie `taken_3`
        """
        sql_query = """
        select count(*) as positive_review_cnt 
        from Reviews 
        where id = 'taken_3' 
        and NLfilter(reviewText, 'the review sentiment is positive')
        """
        return self.execute_thalamusdb_query(sql_query)

    def _execute_q4(self) -> Dict[str, Any]:
        """
        Q4: Positivity ratio of reviews for movie `taken_3`
        """
        sql_query = """
        select 
            cast(sum(case when NLfilter(reviewText, 'the review sentiment is positive') 
                          then 1 else 0 end) as float) / count(*) as positivity_ratio
        from Reviews 
        where id = 'taken_3'
        """
        return self.execute_thalamusdb_query(sql_query)

    def _execute_q5(self) -> Dict[str, Any]:
        """
        Q5: Pairs of reviews that express the *same* sentiment for movie with id `ant_man_and_the_wasp_quantumania`
        """
        sql_query = """
        select R1.id, R1.reviewId as reviewId1, R2.reviewId as reviewId2 
        from Reviews as R1 
        join Reviews as R2 on R1.id = R2.id
        where R1.reviewId <> R2.reviewId
        and R1.id = 'ant_man_and_the_wasp_quantumania' 
        and R2.id = 'ant_man_and_the_wasp_quantumania' 
        and NLjoin(R1.reviewText, R2.reviewText, 'these two movie reviews express the same sentiment - either both are positive or both are negative')
        limit 10
        """
        return self.execute_thalamusdb_query(sql_query)

    def _execute_q6(self) -> Dict[str, Any]:
        """
        Q6: Pairs of reviews that express the *opposite* sentiment for movie with id `ant_man_and_the_wasp_quantumania`
        """
        sql_query = """
        select R1.id, R1.reviewId as reviewId1, R2.reviewId as reviewId2 
        from Reviews as R1 
        join Reviews as R2 on R1.id = R2.id  
        where R1.id = 'ant_man_and_the_wasp_quantumania' 
        and R2.id = 'ant_man_and_the_wasp_quantumania' 
        and R1.reviewId <> R2.reviewId
        and NLjoin(R1.reviewText, R2.reviewText, 'these two movie reviews express opposite sentiments - one is positive and the other is negative')
        limit 10
        """
        return self.execute_thalamusdb_query(sql_query)

    def _execute_q7(self) -> Dict[str, Any]:
        """
        Q7: All Pairs of reviews that express the *opposite* sentiment for movie with id `ant_man_and_the_wasp_quantumania`
        """
        sql_query = """
        select R1.id, R1.reviewId as reviewId1, R2.reviewId as reviewId2 
        from Reviews as R1 
        join Reviews as R2 on R1.id = R2.id  
        where R1.id = 'ant_man_and_the_wasp_quantumania' 
        and R2.id = 'ant_man_and_the_wasp_quantumania' 
        and R1.reviewId <> R2.reviewId
        and NLjoin(R1.reviewText, R2.reviewText, 'these two movie reviews express opposite sentiments - one is positive and the other is negative')
        """
        return self.execute_thalamusdb_query(sql_query)

    def _execute_q8(self) -> Dict[str, Any]:
        """
        Q8: Calculate the number of positive and negative reviews for movie `taken_3`
        """
        sql_query = """
        select 
            case 
                when NLfilter(reviewText, 'the review sentiment is positive') then 'POSITIVE'
                else 'NEGATIVE'
            end as sentiment,
            count(*) as count
        from Reviews 
        where id = 'taken_3'
        group by 
            case 
                when NLfilter(reviewText, 'the review sentiment is positive') then 'POSITIVE'
                else 'NEGATIVE'
            end
        """
        return self.execute_thalamusdb_query(sql_query)
