"""
Created on July 29, 2025

@author: Olga Ovcharenko

ThalamusDB runner implementation for medical use case.
"""

# =============================================================================
# 教学注释 pass — ThalamusDB × medical scenario (SQL-file mode, 跨模态 Q6 中间表)
# =============================================================================
# Medical scenario: 3 表 + audio 设备分类
#   - patients (病人 metadata)
#   - lung_audio (听诊器录音, 3 种 filtration_type: bell/extended/diaphragm)
#   - symptoms_texts (NL 症状描述)
#   - x_ray_images (X-ray image path)
#
# 跟 cars 一样, 这个 runner 没 _execute_q* 方法 — Q1-Q9 全部走
# files/medical/query/thalamusdb/Q*.sql 文件 (SQL-file mode).
#
# 数据建表特殊: 借用 FlockMTLMedicalSetup (跨 SQPE 共享的 setup 工具) →
# db.setup_data(...) 装 4 张主表; ThalamusDB runner *不重新建*, 只加 2 张
# intermediate 表给 Q6 用:
#
#   audio_denorm (pivot): 把 lung_audio 长格式 (1 row 1 audio file) → 宽格式
#     (1 row per (patient_id, location), 3 列 bell/extended/diaphragm audio path).
#     用 MAX(IF(filtration_type='bell', path, NULL)) AS bell_audio 实现 conditional pivot.
#
#   two_more_modalities: 笛卡尔积 patients × audio_denorm × symptoms_texts × x_ray_images,
#     保留 "至少 2 种模态非 NULL" 的 patient row. 跟 cars/two_more_modalities 同思路.
#
# default model = gpt-5-mini (medical 文本量大, gpt-5 系列 long context 性价比好).
#
# skip_setup 参数: 如果用户传 True (e.g. 跑过一次想 reuse 数据), 跳过 setup_data
# 但仍要建 intermediate 表 (因为 intermediate 不持久化).
# =============================================================================

from pathlib import Path
import pandas as pd

# if you use local thalamusdb codes, please uncomment the following codes
import sys

from scenario.medical.setup.flockmtl import FlockMTLMedicalSetup


# sys.path.append(str(Path(__file__).parent.parent.parent.parent))
# tdb_path = str(
#     Path(__file__).parent.parent.parent.parent.parent
#     / "runner"
#     / "generic_thalamusdb_runner"
# )
# print(tdb_path)
# sys.path.insert(0, tdb_path)
# end of local codes version

from runner.generic_thalamusdb_runner.generic_thalamusdb_runner import (
    GenericThalamusDBRunner,
)


class ThalamusDBRunner(GenericThalamusDBRunner):
    """ThalamusDB runner for medical use case."""

    def __init__(
        self,
        use_case: str,
        scale_factor: int,
        model_name: str = "gpt-5-mini",
        concurrent_llm_worker: int = 20,
        skip_setup: bool = False,
    ):
        """
        Initialize ThalamusDB runner for medical case.

        Args:
            use_case: The use case to run
            model_name: LLM model to use
            concurrent_llm_worker: Number of concurrent workers
        """
        # Set database path to medical database
        db_name = "medical_database_tdb.duckdb"

        db_folder = Path(__file__).resolve().parents[5] / "files" / use_case / "data"
        db_path = db_folder / db_name

        # IMPORTANT: Call parent init FIRST to trigger data generation via setup_scenario()
        # This must happen before we try to load CSV files into the database
        super().__init__(
            use_case, scale_factor, model_name, concurrent_llm_worker, db_path,
            skip_setup=skip_setup
        )

        # Now set up the database tables (data should be generated by now)
        db = FlockMTLMedicalSetup(
            db_name=db_name.split(".")[0],
            load_extensions=False,
            db_folder=db_folder,
        )

        # Only setup data if skip_setup is False
        if not skip_setup:
            db.setup_data(
                data_dir=Path(__file__).resolve().parents[5] / "files" / use_case,
                scale_factor=scale_factor
            )

            # Create intermediates for query 6, workaround for WITH ... AS
            create_t1 = """
            CREATE OR REPLACE TABLE audio_denorm AS(
                SELECT patient_id, location, MAX(IF(filtration_type = 'bell', path, NULL)) AS bell_audio, MAX(IF(filtration_type = 'bell', audio_id, NULL)) AS bell_audio_id, MAX(IF(filtration_type = 'extended', path, NULL)) AS extended_audio, MAX(IF(filtration_type = 'extended', audio_id, NULL)) AS extended_audio_id, MAX(IF(filtration_type = 'diaphragm', path, NULL)) AS diaphragm_audio, MAX(IF(filtration_type = 'diaphragm', audio_id, NULL)) AS diaphragm_audio_id FROM lung_audio GROUP BY patient_id, location
            )
            """
            db.run_query(create_t1)

            create_t2 = """
            CREATE OR REPLACE TABLE two_more_modalities AS(
                SELECT patients.patient_id, patients.age, symptoms_texts.symptom_id, symptoms_texts.symptoms, x_ray_images.xray_id, x_ray_images.image_path, audio_denorm.bell_audio_id, audio_denorm.bell_audio, audio_denorm.extended_audio_id, audio_denorm.extended_audio, audio_denorm.diaphragm_audio_id, audio_denorm.diaphragm_audio
                FROM patients
                LEFT JOIN audio_denorm ON patients.patient_id = audio_denorm.patient_id
                LEFT JOIN symptoms_texts ON patients.patient_id = symptoms_texts.patient_id
                LEFT JOIN x_ray_images ON patients.patient_id = x_ray_images.patient_id
                WHERE (audio_denorm.bell_audio_id IS NOT NULL AND symptoms_texts.symptom_id IS NOT NULL) OR (x_ray_images.xray_id IS NOT NULL AND symptoms_texts.symptom_id IS NOT NULL) OR (x_ray_images.xray_id IS NOT NULL AND audio_denorm.bell_audio_id IS NOT NULL)
            )
            """
            db.run_query(create_t2)
