# =============================================================================
# 教学注释 pass — ThalamusDB × mmqa scenario (Hybrid mode, 多 sub-query)
# =============================================================================
# MMQA (Multi-Modal Question Answering) scenario: 4 表 (ap_warrior, movies,
# tampa_airport, images) 跨模态 + 多种 sub-query 类型.
#
# Query 结构特殊: 不是简单 Q1-Q10, 而是 Q2a/Q2b/Q3a-Q3g/Q4-Q7 等带子标号 — 因为
# MMQA paper 是一组 *sub-query 集合*, 不全部能用 ThalamusDB 表达 (SQPE 覆盖能力对比).
#
# 4 个 unsupported (NotImplementedError):
#   - Q1, Q2b, Q4, Q5: 需要 "semantic extract / map / summarize" 算子, ThalamusDB
#     只有 NLfilter / NLjoin 不支持 extract (e.g. "把 description 抽出 director 名字").
#     SemBench 拿这做 SQPE 能力对比 (Palimpzest / LOTUS 能跑这些 Q, ThalamusDB 不能).
#
# 14 个 supported:
#   - Q2a: NLjoin (track 名 ↔ logo image)
#   - Q3a-Q3g: 7 个 NLfilter 同表不同 condition (genre 分类)
#   - Q6a/b/c: NLfilter (airline 飞往 X 的目的地)
#   - Q7: NLjoin (airline 名 ↔ logo image)
#
# 数据 setup 用 _add_table → read_csv_auto, 跟其它 scenario 的 `register + CREATE TABLE`
# 略不同 (这里更简洁, 但走 DuckDB 内置 CSV 解析).
# =============================================================================
import os
from pathlib import Path
from typing import Any, Dict

import duckdb

from runner.generic_thalamusdb_runner.generic_thalamusdb_runner import (
    GenericThalamusDBRunner,
)


class ThalamusDBRunner(GenericThalamusDBRunner):
    """ThalamusDB runner for the MMQA scenario."""

    def __init__(
        self,
        use_case: str,
        scale_factor: int,
        model_name: str = "gemini-2.5-flash",
        concurrent_llm_worker: int = 20,
        skip_setup: bool = False,
    ):
        """
        Initialize ThalamusDB runner for the MMQA scenario.

        Args:
            use_case: The use case to run
            model_name: LLM model to use
            concurrent_llm_worker: Number of concurrent workers
        """

        # Set database path to `mmqa_thalamusdb` database
        db_name = "mmqa_thalamusdb.duckdb"
        db_folder = (
            Path(__file__).resolve().parents[5] / "files" / use_case / "data" / f"sf_{scale_factor}"
        )
        db_path = db_folder / db_name

        # IMPORTANT: Call parent init FIRST to trigger data generation via setup_scenario()
        # This must happen before we try to read CSV files
        super().__init__(
            use_case, scale_factor, model_name, concurrent_llm_worker, db_path,
            skip_setup=skip_setup
        )

        # Now create the tables if they don't exist (data should be generated by now)
        # Note: The database file may already exist (created by parent init),
        # so we check for tables instead of file existence
        conn = duckdb.connect(db_path)
        tables = conn.execute("SHOW TABLES").fetchall()

        if len(tables) == 0:
            self.conn = conn
            self._setup_data(data_dir=db_folder)
        else:
            conn.close()

    def _add_table(self, csv_filepath: str, table_name: str) -> None:
        if not os.path.exists(csv_filepath):
            raise FileNotFoundError(f"CSV file not found: {csv_filepath}")

        self.conn.execute(
            f"CREATE TABLE IF NOT EXISTS {table_name} AS SELECT * FROM read_csv_auto('{csv_filepath}')"  # noqa: E501
        )

    def _setup_data(self, data_dir: str) -> None:
        self._add_table(
            os.path.join(data_dir, "ap_warrior.csv"),
            table_name="ap_warrior",
        )

        self._add_table(
            os.path.join(data_dir, "lizzy_caplan_text_data.csv"),
            table_name="movies",
        )

        self._add_table(
            os.path.join(data_dir, "tampa_international_airport.csv"),
            table_name="tampa_airport",
        )

        self._add_table(
            os.path.join(data_dir, "thalamusdb_images.csv"),
            table_name="images",
        )

    def _execute_q1(self):
        raise NotImplementedError(
            "ThalamusDB does not currently support semantic extract/map operators."  # noqa: E501
        )

    def _execute_q2a(self) -> Dict[str, Any]:
        query = """
            SELECT t.ID AS 'ID', image_filename AS image_id
            FROM ap_warrior t, images i
            WHERE NLjoin(t.Track, i.image_filepath, 'the image shows the logo of the horse racetrack');
        """  # noqa: E501

        return self.execute_thalamusdb_query(query)

    def _execute_q2b(self) -> Dict[str, Any]:
        raise NotImplementedError(
            "ThalamusDB does not currently support semantic extract/map operators."  # noqa: E501
        )

    def _execute_q3a(self) -> Dict[str, Any]:
        query = """
            SELECT title FROM movies WHERE NLfilter(text, 'the movie is a comedy');
        """  # noqa: E501

        return self.execute_thalamusdb_query(query)

    def _execute_q3b(self) -> Dict[str, Any]:
        query = """
            SELECT title FROM movies WHERE NLfilter(text, 'the movie is a sci-fi movie');
        """  # noqa: E501

        return self.execute_thalamusdb_query(query)

    def _execute_q3c(self) -> Dict[str, Any]:
        query = """
            SELECT title FROM movies WHERE NLfilter(text, 'the movie is a romance movie');
        """  # noqa: E501

        return self.execute_thalamusdb_query(query)

    def _execute_q3d(self) -> Dict[str, Any]:
        query = """
            SELECT title FROM movies WHERE NLfilter(text, 'the movie is a horror movie');
        """  # noqa: E501

        return self.execute_thalamusdb_query(query)

    def _execute_q3e(self) -> Dict[str, Any]:
        query = """
            SELECT title FROM movies WHERE NLfilter(text, 'the movie is a heist movie');
        """  # noqa: E501

        return self.execute_thalamusdb_query(query)

    def _execute_q3f(self) -> Dict[str, Any]:
        query = """
            SELECT title FROM movies WHERE NLfilter(text, 'the movie is a romantic comedy');
        """  # noqa: E501

        return self.execute_thalamusdb_query(query)

    def _execute_q3g(self) -> Dict[str, Any]:
        query = """
            SELECT title FROM movies WHERE NLfilter(text, 'the movie is a biographical comedy');
        """  # noqa: E501

        return self.execute_thalamusdb_query(query)

    def _execute_q4(self):
        raise NotImplementedError(
            "ThalamusDB does not currently support semantic extract/map operators."  # noqa: E501
        )

    def _execute_q5(self):
        raise NotImplementedError(
            "ThalamusDB does not currently support semantic map/summarize operators."  # noqa: E501
        )

    def _execute_q6a(self) -> Dict[str, Any]:
        query = """
            SELECT Airlines AS 'Airlines' FROM tampa_airport WHERE NLfilter(Destinations, 'the airline has flights to Frankfurt');
        """  # noqa: E501

        return self.execute_thalamusdb_query(query)

    def _execute_q6b(self) -> Dict[str, Any]:
        query = """
            SELECT Airlines AS 'Airlines' FROM tampa_airport WHERE NLfilter(Destinations, 'the airline has flights to Germany');
        """  # noqa: E501

        return self.execute_thalamusdb_query(query)

    def _execute_q6c(self) -> Dict[str, Any]:
        query = """
            SELECT Airlines AS 'Airlines' FROM tampa_airport WHERE NLfilter(Destinations, 'the airline has flights to Europe');
        """  # noqa: E501

        return self.execute_thalamusdb_query(query)

    def _execute_q7(self) -> Dict[str, Any]:
        query = """
            SELECT t.Airlines AS 'Airlines', i.image_filename AS image_id
            FROM tampa_airport t, images i
            WHERE NLjoin(t.Airlines, i.image_filepath, 'the image shows the airline logo');
        """  # noqa: E501

        return self.execute_thalamusdb_query(query)
